import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Stock } from '../src/lib/stocks';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.join(__dirname, '..');

const STOCKS_FILE = path.join(__dirname, 'us-stocks.json');
const SEED_FILE = path.join(projectRoot, 'supabase', 'seed.sql');

function escapeSql(str: string): string {
  if (typeof str !== 'string') return str;
  return str.replace(/'/g, "''");
}

function generateStocksSql(stocks: Stock[]): string {
  if (stocks.length === 0) return '';
  
  const values = stocks
    .map(
      (s) =>
        `('${escapeSql(s.symbol)}', '${escapeSql(s.name)}', '${escapeSql(s.exchange)}')`
    )
    .join(',\n  ');

  return `
INSERT INTO public.stocks (symbol, name, exchange)
VALUES
  ${values}
ON CONFLICT (symbol) DO NOTHING;
`;
}

async function main() {
  console.log('Generating supabase/seed.sql...');

  // 1. Read Data
  let stocksData;
  try {
    stocksData = JSON.parse(fs.readFileSync(STOCKS_FILE, 'utf-8'));
  } catch (error) {
    throw new Error(`Failed to read ${STOCKS_FILE}: ${error instanceof Error ? error.message : error}`);
  }

  const stocks = stocksData.data || [];

  // 2. Generate SQL
  const stocksSql = generateStocksSql(stocks);

  const fullSql = `/*
  Auto-generated seed file. 
  Generated by scripts/generate-seed.ts
  Do not edit manually.
*/

-- 1. Stocks
${stocksSql}
`;

  // 3. Write File
  fs.writeFileSync(SEED_FILE, fullSql);
  
  console.log(`✅ seed.sql generated at ${SEED_FILE}`);
  console.log(`   - ${stocks.length} stocks`);
}

main().catch(console.error);
